require("scripts.const")

require("prototypes.category")
require("prototypes.items")
require("prototypes.signals")
require("prototypes.entities")
require("prototypes.components")
require("prototypes.sounds")
require("prototypes.recipes")
require("prototypes.styles")
